
server:
  port: 8080
#    context-path: /drp

spring:
  datasource:
    #    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://81.70.180.73:3306/br_bangong?characterEncoding=utf-8
    #url: jdbc:mysql://8.129.51.229:3306/k?characterEncoding=utf-8
    username: boran1
    password: boran123
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
  servlet:
    multipart:
      max-file-size: 1050MB
      max-request-size: 1050MB
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml  #mybatis指定数据库xml文件
  typeAliasesPackage: com.example.drp.Entity      #指定实体类
  configuration:
    map-underscore-to-camel-case: false  #关闭驼峰，实体类的 *_*映射
    auto-mapping-behavior: full
    use-generated-keys: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      column-underline: true
      logic-delete-value: 0
      logic-not-delete-value: 1
    refresh: true

##jwt配置
audience:
  # 代表这个JWT的接收对象,存入audience
  clientId: 098f6bcd4621d373cade4e832627b4f6
  # 密钥, 经过Base64加密, 可自行替换
  base64Secret: MDk4ZjZiY2Q0NjIxZDM3M2NhZGU0ZTgzMjYyN2I0ZjY=
  # JWT的签发主体，存入issuer
  name: restapiuser
  # 过期时间，时间戳
  expiresSecond: 172800
#自定义的配置

